create table people (id INTEGER, name VARCHAR(200), age INTEGER);
insert into people(id, name, age) values (1, 'sharon', 38);
insert into people(id, name, age) values (2, 'bop', 32);
insert into people(id, name, age) values (3, 'james', 38);
create table people2 (id INTEGER, name VARCHAR(200), age INTEGER);
insert into people2(id, name, age) values (1, 'bob', 10);
insert into people2(id, name, age) values(2, 'larry', 15);
create table people3 (id INTEGER, name VARCHAR(100));
insert into people3(id, name) values (1, 'kim');
insert into people3(id, name) values(2, 'jim');
create table people4 (id INTEGER, name VARCHAR(200), age INTEGER);
create table people5 (id INTEGER, name VARCHAR(200), age INTEGER);
insert into people5(id, name, age) values (1, 'sharon', 38);
insert into people5(id, name, age) values (2, 'bop', 30);
insert into people5(id, name, age) values (3, 'jim', 38);
create table people6 (id INTEGER PRIMARY KEY, name VARCHAR(200), age INTEGER);
insert into people6(id, name, age) values (1, 'slambson', 38);
insert into people6(id, name, age) values (2, 'slambsonian', 32);
insert into people6(id, name, age) values (3, 'slam', 38);
create table people7 (id INTEGER PRIMARY KEY, name VARCHAR(200), age INTEGER);